// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HopInLine.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240831021716_UpdateLineAndParticipantModel")]
    partial class UpdateLineAndParticipantModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.33");

            modelBuilder.Entity("HopInLine.Data.Line.Line", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("AutoAdvanceInterval")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoAdvanceLine")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoReAdd")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CountDownStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lines");
                });

            modelBuilder.Entity("HopInLine.Data.Line.Participant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("LineId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LineId1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Removed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TurnCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LineId");

                    b.HasIndex("LineId1");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("HopInLine.Data.Line.Participant", b =>
                {
                    b.HasOne("HopInLine.Data.Line.Line", null)
                        .WithMany("Participants")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HopInLine.Data.Line.Line", null)
                        .WithMany("RemovedParticipants")
                        .HasForeignKey("LineId1");
                });

            modelBuilder.Entity("HopInLine.Data.Line.Line", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("RemovedParticipants");
                });
#pragma warning restore 612, 618
        }
    }
}
